### ISSUE TITLE
Search enhancements

### ISSUE THREAD

**Issue by pedrohr** [alliance-genome/agr_prototype#39]
This is issue should contain all the desired search enhancements for the prototype. We will keep this updated as long as items get solved.

1) Searching for genes using the gene ID
For example, if I search for "da", I get two FlyBase/Drosophila genes with respective IDs "FBgn0267821" and "FBgn0019829". Currently, I cannot search using either of these IDs to find the respective genes. Same goes for genes from other species, for example I cannot search for WormBase genes using the WBGene ID (e.g. "WBGene00000001").

2) Searching for GO terms using the GO ID
Similar issue as for genes above. For example, cannot search for GO term "cytokinesis" using the ID for the term, "GO:0000910"

3) Searching for disease using the OMIM ID
Again, similar issue. Cannot search for Alzheimer's disease using OMIM ID: 606889

4) Searching for GO terms or disease terms using synonyms
For example, cannot search for "cytokinesis" using the synonym "cell cycle cytokinesis"; cannot search for "Alzheimer's disease" using synonym "ALZHEIMER DISEASE, FAMILIAL, 4"

5) Display of gene genomic coordinates
In the gene table view, there are columns "Genomic Coordinates" and "Relative Coordinates" (I'm not sure of the difference), but no data for them

6) Display of GO term synonyms and GO term IDs
The display of GO terms does not include term synonyms or GO IDs; for example, "cytokinesis" GO term does not display its ID (GO:0000910) or synonyms (cell cycle cytokinesis, cytokinesis involved in cell cycle)

7) Display of disease synonyms
For example "ALZHEIMER DISEASE, FAMILIAL, 4" for OMIM ID: 606889

8) Orthology data
We've already discussed this and is being worked on in ticket #35

9) Text based filtering of results
From the use case: "Each set of results would also have an input box for filtering the results with text, narrowing down the displayed results to those that have matches of the filter text to text within any presented data field."

10) Download options

11) "Results can also be sorted (alphanumerically) by data field."
Sorting results, preferably by column/data field

12) Items from auto-complete should consider the whole sentence. Example: using the autocomplete to choose “regulation of heart contraction” should consider the whole sentence

**Comment by pedrohr** [comment]
1-9 and 12 is done

**Comment by chris-grove** [comment]
@pedrohr 
It's looking great! Thanks for all the updates.

I think we're still missing the display of GO term IDs from issue number 6 (the IDs show up as matching hits when you search using a GO ID, but the ID doesn't show up in the results otherwise) and I don't think the text search boxes have been implemented for issue number 9. What I/we was/were thinking for 9 was something similar to what we already have implemented at WormBase, for example in the hlh-2 gene page in WormBase:

http://www.wormbase.org/species/c_elegans/gene/WBGene00001949#0c--10

The "Phenotypes" widget allows the user to type text to limit the number of hits (phenotypes in this case) to only those that match the input text.

All that being said, I don't know whether either of those issues are hugely important, especially for the first prototype, but it's worth noting as an exercise.

**Comment by pedrohr** [comment]
@chris-grove 
you are right for #6 I literally just associated it with searching by ids and I thought it was done, we are changing that right now.

And for #9 you can limit the results by filtering the facets. It has the same effect.

**Comment by pedrohr** [comment]
Ok, now #6 is there.

**Comment by chris-grove** [comment]
@pedrohr 
OK, great. Can we add GO IDs to the table view as well as the list view?

**Comment by gabinkley** [comment]
Yep, similar to how OMIM ids show up for in both the table and list views.  Thanks @chris-grove

**Comment by gabinkley** [comment]
#1-8 are done
#9 you can limit the results by filtering the facets. It has the same effect. 
#10-11 are not necessary to complete for the prototype discussion
#12 autocomplete will consider anything within ""

Closing.
Other ideas and suggestions should be added to either #36 or #37

**Comment by chris-grove** [comment]
@gabinkley 
A couple of points:
As for number 9, the filtering of the facets, as far as I can tell, is not quite what we had in mind when writing the use case. The existing filtering allows a user to filter down the list of existing facets, but doesn't allow a user to enter any free text to search for a match in displayed fields, as one is capable of doing in the WormBase example I gave above. We can discuss whether we really need or want that functionality, but for the record what is there in the prototype isn't the same thing as what was requested.

As for GO IDs, they still are not showing up in the table view, as far as I can tell. They only display in the list view. Again, I'm not going to suggest that everything be held up because of that, but I wanted to make that clear.

These can both be added as separate tickets later if we see the need.
